---
- name: Qtile | Reload Qtile config
  ansible.builtin.command: qtile cmd-obj -o cmd -f reload_config
  notify: Qtile | Restart Qtile
  register: reload_qtile
  changed_when: reload_qtile.rc != 0

- name: Qtile | Restart Qtile
  ansible.builtin.command: qtile cmd-obj -o cmd -f restart
  register: restart_qtile
  changed_when: restart_qtile.rc != 0
