---
- name: System | Setup cron
  block:
    - name: System | Install cronie
      community.general.pacman:
        name: cronie
        state: present
      become: true

    - name: System | Start cronie
      ansible.builtin.service:
        name: cronie
        enabled: true
      become: true

- name: System | Select best mirrors list
  block:
    - name: System | Install reflector
      community.general.pacman:
        name: reflector
        state: present
      become: true

    - name: System | Enable reflector
      ansible.builtin.cron:
        name: reflector
        special_time: daily
        job: reflector  --verbose \
          --sort rate \
          --age 24 \
          --protocol https \
          --country France \
          --threads {{ ansible_facts.processor_vcpus }} \
          --save /etc/pacman.d/mirrorlist

- name: System | Update Repositories
  community.general.pacman:
    update_cache: true
  become: true

- name: System | Check Packages
  ansible.builtin.shell: pacman -Qu 2>&1
  register: upgrade_check
  changed_when: false
  ignore_errors: yes

- name: System | Print Packages to Upgrade
  debug:
    msg: "{{ upgrade_check.stdout_lines }}"
  when: upgrade_check.stdout != ""

- name: System | Confirm Packages Upgrade
  pause_styled:
    prompt: "Are you sure you want to continue? (y/n)"
  register: confirm_upgrade
  when: upgrade_check.stdout != ""

- name: System | Upgrade Packages
  community.general.pacman:
    upgrade: true
  become: true
  when: upgrade_check.stdout != "" and confirm_upgrade.user_input == "y"

- name: System | Set hosts
  ansible.builtin.template:
    dest: "/etc/hosts"
    src: hosts.j2
    mode: "0644"
  become: true
