[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#575860"
blue = "#86abdc"
cyan = "#7ad5d6"
green = "#8ebaa4"
magenta = "#baa1e2"
red = "#d16983"
white = "#e4e4e5"
yellow = "#e0c989"

[colors.normal]
black = "#393b44"
blue = "#719cd6"
cyan = "#63cdcf"
green = "#81b29a"
magenta = "#9d79d6"
red = "#c94f6d"
white = "#dfdfe0"
yellow = "#dbc074"

[colors.primary]
background = "#192330"
foreground = "#cdcecf"

[colors.cursor]
cursor = "#719cd6"
text = "CellBackground"

[colors.selection]
background = "#393b44"
text = "CellForeground"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[font.offset]
x = 0
y = 1

[keyboard]
bindings = [
    { mods = "Control|Shift", key = "V", action = "Paste" },
    { mods = "Control|Shift", key = "C", action = "Copy" },
    { mods = "None", key = "Paste", action = "Paste" },
    { mods = "None", key = "Copy", action = "Copy" },
    { mods = "Shift", key = "Insert", action = "PasteSelection" },
    { mods = "Control", key = "Key0", action = "ResetFontSize" },
    { mods = "Control", key = "=", action = "IncreaseFontSize" },
    { mods = "Control", key = "-", action = "DecreaseFontSize" },
    { mods = "None", key = "F11", action = "ToggleFullScreen" },
    { mods = "Control", key = "L", action = "ClearLogNotice" },
    { mods = "Control", key = "L", chars = "\f" },
    { mods = "None", key = "PageUp", mode = "~Alt", action = "ScrollPageUp" },
    { mods = "None", key = "PageDown", mode = "~Alt", action = "ScrollPageDown" },
    { mods = "Shift", key = "Home", mode = "~Alt", action = "ScrollToTop" },
    { mods = "Shift", key = "End", mode = "~Alt", action = "ScrollToBottom" }
]

[scrolling]
history = 10000

[window]
dynamic_padding = false
opacity = 1.0
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6
