---
- name: Alacritty | Install Alacritty
  community.general.pacman:
    name: alacritty
    state: present
  become: true

- name: Alacritty | Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/alacritty"
    state: directory

- name: Alacritty | Create symlink to config
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/alacritty"
    state: link
    force: true
